/**
 * MCP App Client: LifePilot
 *
 * This script runs inside the MCP App iframe and communicates with the MCP host.
 * It displays the plan generated by the LifePilot server tool.
 *
 * The App class from @modelcontextprotocol/ext-apps handles all PostMessageTransport
 * communication with the host automatically.
 */

import { App } from '@modelcontextprotocol/ext-apps';
import type { CallToolResult } from '@modelcontextprotocol/client';

interface Plan {
  goal: string;
  context: string;
  tasks: string[];
  nextSteps: string[];
  followups: string[];
  informationNeeded: string[];
}

/**
 * Extract plan from tool result
 */
function extractPlan(result: CallToolResult): Plan | null {
  const content = result.structuredContent as Plan | undefined;
  if (content && typeof content === 'object') {
    return content as Plan;
  }
  return null;
}

/**
 * Render plan to the DOM
 */
function renderPlan(plan: Plan): void {
  const container = document.getElementById('plan-container');
  if (!container) return;

  const html = `
    <div class="plan-section">
      <h2>Goal</h2>
      <p>${escapeHTML(plan.goal)}</p>
      <p><strong>Context:</strong> ${escapeHTML(plan.context)}</p>
    </div>

    <div class="plan-section">
      <h2>Tasks</h2>
      <ul>
        ${plan.tasks.map((task) => `<li>${escapeHTML(task)}</li>`).join('')}
      </ul>
    </div>

    <div class="plan-section">
      <h2>Next Steps</h2>
      <ul>
        ${plan.nextSteps.map((step) => `<li>${escapeHTML(step)}</li>`).join('')}
      </ul>
    </div>

    <div class="plan-section">
      <h2>Follow-ups</h2>
      <ul>
        ${plan.followups.map((f) => `<li>${escapeHTML(f)}</li>`).join('')}
      </ul>
    </div>

    ${
      plan.informationNeeded.length > 0
        ? `
      <div class="plan-section">
        <h2>Information Needed</h2>
        <ul>
          ${plan.informationNeeded.map((info) => `<li>${escapeHTML(info)}</li>`).join('')}
        </ul>
      </div>
    `
        : ''
    }
  `;

  container.innerHTML = html;
}

/**
 * Escape HTML to prevent XSS
 */
function escapeHTML(text: string): string {
  const div = document.createElement('div');
  div.textContent = text;
  return div.innerHTML;
}

/**
 * Render error message
 */
function renderError(message: string): void {
  const container = document.getElementById('plan-container');
  if (!container) return;

  container.innerHTML = `
    <div class="error">
      <strong>Error:</strong> ${escapeHTML(message)}
    </div>
  `;
}

// ============================================================================
// INITIALIZE MCP APP
// ============================================================================

// Create App instance
const app = new App({ name: 'LifePilot', version: '1.0.0' });

// Handle tool input (when the host invokes the tool)
app.ontoolinput = (params) => {
  console.info('[LifePilot] Tool input received:', params);
};

// Handle tool result (plan generated by server)
app.ontoolresult = (result: CallToolResult) => {
  console.info('[LifePilot] Tool result received:', result);

  const plan = extractPlan(result);
  if (plan) {
    renderPlan(plan);
  } else if (result.isError) {
    renderError('Failed to generate plan');
  } else {
    renderError('Unexpected response format');
  }
};

// Handle tool cancellation
app.ontoolcancelled = (params) => {
  console.info('[LifePilot] Tool cancelled:', params.reason);
  renderError(`Plan generation cancelled: ${params.reason}`);
};

// Handle errors
app.onerror = (error) => {
  console.error('[LifePilot] App error:', error);
  renderError('An unexpected error occurred');
};

// Handle host context changes (theme, styling, etc.)
app.onhostcontextchanged = (context) => {
  console.info('[LifePilot] Host context changed:', context);
  // Could apply theming, adjust layout for safe area insets, etc.
};

// Handle app teardown
app.onteardown = async () => {
  console.info('[LifePilot] App is being torn down');
  return {};
};

// Connect to host
app.connect().then(() => {
  console.info('[LifePilot] Connected to MCP host');
});
